

DROP TABLE EXAM_TBL;
DROP TABLE CLASS_TBL;

CREATE TABLE CLASS_TBL (
    CLASS_NO NUMBER NOT NULL,
    CLASS_NAME VARCHAR2(12 BYTE),
    CLASS_AGE NUMBER,
    CONSTRAINT PK_CLASS PRIMARY KEY(CLASS_NO)
);

CREATE TABLE EXAM_TBL (
    EXAM_NO NUMBER NOT NULL,
    CLASS_NO NUMBER,
    SUBJECTCODE_ VARCHAR2(12 BYTE),
    CONSTRAINT PK_EXAM PRIMARY KEY(CLASS_NO),
    CONSTRAINT FK_EXAM_CLASS FOREIGN KEY(CLASS_NO) REFERENCES CLASS_TBL(CLASS_NO)
);
    
    