
DROP TABLE CUSTOMER_TBL;
DROP TABLE BANK_TBL;


CREATE TABLE BANK_TBL (
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE),
    CONSTRAINT PK_BANK_CODE PRIMARY KEY(BANK_CODE)
);

CREATE TABLE CUSTOMER_TBL (
    NO NUMBER NOT NULL,
    NAME VARCHAR2(30 BYTE),
    PHONE VARCHAR2(30 BYTE) UNIQUE,
    AGE NUMBER  CHECK(AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20 BYTE),
    CONSTRAINT PK_NO PRIMARY KEY(NO),
    CONSTRAINT FK_BANK_CODE FOREIGN KEY(BANK_CODE) REFERENCES BANK_TBL(BANK_CODE);
