DROP TABLE EXAM_TBL;
DROP TABLE STU_TBL;
DROP TABLE CLASS_TBL;

CREATE TABLE CLASS_TBL (
    CLASS_NO NUMBER NOT NULL,
    CLASS_NAME VARCHAR2(12 BYTE),
    CLASS_AGE NUMBER,
    CONSTRAINT PK_CLASS PRIMARY KEY(CLASS_NO)
);

CREATE TABLE STU_TBL (
    SUBJECT_CODE VARCHAR2(12 BYTE),
    SUBJECT_NAME VARCHAR2(12 BYTE),
    PERSON_NAME VARCHAR2(12 BYTE),
    CONSTRAINT PK_SUBJECT_CODE PRIMARY KEY(SUBJECT_CODE)
);
    

CREATE TABLE EXAM_TBL (
    EXAM_NO NUMBER NOT NULL,
    CLASS_NO NUMBER,
    SUBJECT_CODE VARCHAR2(10 BYTE),
    CONSTRAINT PK_EXAM PRIMARY KEY(EXAM_NO),
    CONSTRAINT FK_CLASS_NO FOREIGN KEY(CLASS_NO) REFERENCES CLASS_TBL(CLASS_NO),
    CONSTRAINT FK_SUBJECT_CODE FOREIGN KEY(SUBJECT_CODE) REFERENCES STU_TBL(SUBJECT_CODE)
);


    
    