DROP TABLE LECTURE_TBL;
DROP TABLE ENROLL_TBL;
DROP TABLE COURSE_TBL;
DROP TABLE STUDENT_TBL;
DROP TABLE PROFESSOR_TBL;

CREATE TABLE PROFESSOR_TBL (
    PRO_NO NUMBER NOT NULL,
    PRO_NAME VARCHAR2(10 BYTE),
    PRO_MAJOR VARCHAR2(20 BYTE)
);


CREATE TABLE STUDENT_TBL (
    STU_NO NUMBER NOT NULL,
    STU_NAME VARCHAR2(10 BYTE),
    STU_ADD VARCHAR2(30 BYTE),
    STU_GRADE NUMBER,
    PRO_NO NUMBER
);

CREATE TABLE COURSE_TBL (
    SUBJECT_NO NUMBER NOT NULL,
    SUBJECT_NAME VARCHAR2(15 BYTE),
    CREDIT NUMBER
);

CREATE TABLE ENROLL_TBL (
    CLASS_NO NUMBER NOT NULL,
    STU_NO NUMBER NOT NULL,
    SUBJECT_NO NUMBER,
    CLASS_DATE VARCHAR2(15 BYTE)
);

CREATE TABLE LECTURE_TBL (
    LT_NO NUMBER NOT NULL,
    PRO_NO NUMBER,
    CLASS_NO NUMBER,
    LT_NAME VARCHAR2(20 BYTE),
    LT_ROOM VARCHAR2(10 BYTE)
);

-- 기본키 추가하기
ALTER TABLE PROFESSOR_TBL
    ADD CONSTRAINT PK_PRO_NO PRIMARY KEY(PRO_NO);
ALTER TABLE STUDENT_TBL
    ADD CONSTRAINT PK_STU_NO PRIMARY KEY(STU_NO);
ALTER TABLE COURSE_TBL
    ADD CONSTRAINT PK_SUBJECT_NO PRIMARY KEY(SUBJECT_NO);
ALTER TABLE ENROLL_TBL
    ADD CONSTRAINT PK_CLASS_NO PRIMARY KEY(CLASS_NO);
ALTER TABLE LECTURE_TBL
    ADD CONSTRAINT PK_LT_NO PRIMARY KEY(LT_NO);
    
-- 외래키 추가하기
ALTER TABLE STUDENT_TBL
    ADD CONSTRAINT FK_PRO_NO FOREIGN KEY(PRO_NO)
        REFERENCES PROFESSOR_TBL(PRO_NO)
            ON DELETE SET NULL;
ALTER TABLE ENROLL_TBL
    ADD CONSTRAINT FK_STU_NO FOREIGN KEY(STU_NO)
        REFERENCES STUDENT_TBL(STU_NO)
            ON DELETE SET NULL;
ALTER TABLE ENROLL_TBL
    ADD CONSTRAINT FK_SUBJECT_NO FOREIGN KEY(SUBJECT_NO)
        REFERENCES COURSE_TBL(SUBJECT_NO)
            ON DELETE SET NULL;
ALTER TABLE LECTURE_TBL
    ADD CONSTRAINT FK_PRO FOREIGN KEY(PRO_NO)
        REFERENCES PROFESSOR_TBL(PRO_NO)
            ON DELETE SET NULL;
ALTER TABLE LECTURE_TBL
    ADD CONSTRAINT FK_CLASS FOREIGN KEY(CLASS_NO)
        REFERENCES ENROLL_TBL(CLASS_NO)
            ON DELETE SET NULL;











